version: "3.9"

services:
  app:
    build: .
    command: yarn run dev
    container_name: portal
    restart: always
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules